# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('language', models.IntegerField(choices=[(0, 'english'), (1, 'polish'), (2, 'german'), (3, 'french'), (4, 'russian')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('general_ratings', models.IntegerField(choices=[(0, 'bad'), (1, 'meh'), (2, 'good')], default=None)),
                ('politics', models.IntegerField(choices=[(0, 'not at all'), (1, 'a bit'), (2, 'evenly with other topics'), (3, 'dominates others'), (4, 'speaks only about it')], default=None)),
                ('sports', models.IntegerField(choices=[(0, 'not at all'), (1, 'a bit'), (2, 'evenly with other topics'), (3, 'dominates others'), (4, 'speaks only about it')], default=None)),
                ('culture', models.IntegerField(choices=[(0, 'not at all'), (1, 'a bit'), (2, 'evenly with other topics'), (3, 'dominates others'), (4, 'speaks only about it')], default=None)),
                ('tech', models.IntegerField(choices=[(0, 'not at all'), (1, 'a bit'), (2, 'evenly with other topics'), (3, 'dominates others'), (4, 'speaks only about it')], default=None)),
                ('travel', models.IntegerField(choices=[(0, 'not at all'), (1, 'a bit'), (2, 'evenly with other topics'), (3, 'dominates others'), (4, 'speaks only about it')], default=None)),
                ('fashion', models.IntegerField(choices=[(0, 'not at all'), (1, 'a bit'), (2, 'evenly with other topics'), (3, 'dominates others'), (4, 'speaks only about it')], default=None)),
                ('hard_science', models.IntegerField(choices=[(0, 'not at all'), (1, 'a bit'), (2, 'evenly with other topics'), (3, 'dominates others'), (4, 'speaks only about it')], default=None)),
                ('soft_science', models.IntegerField(choices=[(0, 'not at all'), (1, 'a bit'), (2, 'evenly with other topics'), (3, 'dominates others'), (4, 'speaks only about it')], default=None)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
