# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_blogs', models.ManyToManyField(to='blogs.Blog')),
                ('followers', models.ManyToManyField(related_name='_userfollowings_followers_+', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='_userfollowings_following_+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
