# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='coefficients',
            field=models.CharField(default='', max_length=200),
        ),
    ]
