# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20161003_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowings',
            name='culture',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfollowings',
            name='fashion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfollowings',
            name='hard_science',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfollowings',
            name='politics',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfollowings',
            name='soft_science',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfollowings',
            name='sports',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfollowings',
            name='tech',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userfollowings',
            name='travel',
            field=models.FloatField(default=0),
        ),
    ]
