# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20161018_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictrating',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
