# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_predictrating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_calculated', models.DateTimeField(default=datetime.datetime(2010, 1, 1, 0, 0, tzinfo=utc))),
            ],
        ),
    ]
