# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ups',
            field=models.IntegerField(null=True),
        ),
    ]
