# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20161010_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='binom',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
    ]
