# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comment_binom'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ups',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
